version: '3.3'

services:

   scalyr:
     image: scalyr/scalyr-docker-agent
     volumes:
     - ${WEBAPP_STORAGE_HOME}/scalyr-agent-2/agent.d:/etc/scalyr-agent-2/agent.d
     - ${WEBAPP_STORAGE_HOME}/LogFiles:/etc/scalyr-agent-2/scalyr-agent-2/container
     - /var/run/docker.sock:/var/scalyr/docker.sock


