version: '3.3'

services:

   scalyr:
      image: scalyr/scalyr-docker-agent
      volumes:
      - ${WEBAPP_STORAGE_HOME}/scalyr-agent-2/agent.d:/etc/scalyr-agent-2/agent.d
      - ${WEBAPP_STORAGE_HOME}/LogFiles:/var/log/scalyr-agent-2/container
      - /var/run/docker.sock:/var/scalyr/docker.sock
      ports:
      - 601:601

   db:
     image: mysql:5.7
     volumes:
       - ${WEBAPP_STORAGE_HOME}/db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     depends_on:
       - scalyr

   wordpress:
     depends_on:
       - db
       - scalyr
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
volumes:
    db_data:
