version: '3.3'

services:

   scalyr:
     image: scalyr/scalyr-docker-agent
     volumes:
     - ${WEBAPP_STORAGE_HOME}/scalyr-agent-2/agent.d:/etc/scalyr-agent-2/agent.d
     - ${WEBAPP_STORAGE_HOME}/LogFiles:/var/log/scalyr-agent-2/container
     ports:
     - 601:601

